name: Pipeline Laravel & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  # ÉTAPE 1 : Validation du code Laravel (CI)
  test-app:
    name: Laravel Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projet-produits

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, curl, sqlite, pdo_sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env for testing
        # On crée un .env minimal pour que Laravel ne cherche pas MySQL durant les tests
        run: |
          echo "APP_KEY=base64:u689u9v6Y7Y7986V876v876v876v876v876v876v876=" > .env
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=:memory:" >> .env

      - name: Run Tests
        run: |
          php artisan migrate --force
          php artisan test

  # ÉTAPE 2 : Construction de l'image Docker (seulement si le test passe)
  build-docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [test-app] 
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          # On définit le contexte sur le dossier du projet
          context: ./projet-produits
          file: ./projet-produits/Dockerfile
          push: true
          tags: julespecquereau/laravel-app:latest

  
  github-runner:
    name: Github runner 
    runs-on: self-hosted
    needs: build-docker
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: docker compose up
        working-directory: ./projet-produits
        run: docker compose up -d 
