name: Pipeline Laravel & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  # ÉTAPE 1 : Validation du code Laravel
  test-app:
    name: Laravel Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projet-produits

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, curl, sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Create .env file from Secret
        run: echo "${{ secrets.DOT_ENV }}" > .env

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: |
          # Maintenant que le fichier existe, key:generate peut écrire dedans
          php artisan key:generate
          php artisan test

  # ÉTAPE 2 : Construction de l'image Docker (seulement si le test passe)
  build-docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [test-app] # <--- Sécurité : si le test échoue, on ne build pas
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Vérifie le chemin du Dockerfile de ton binôme
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest