name: Pipeline Laravel & Docker

on:
  push:
    branches: [ "main" ]

jobs:
  # Ã‰TAPE 1 : Validation du code Laravel
  test-app:
    name: ğŸ§ª Laravel Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./projet-produits

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, curl, sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:" # Plus simple pour les tests rapides
        run: |
          php artisan key:generate
          php artisan test

  # Ã‰TAPE 2 : Construction de l'image Docker (seulement si le test passe)
  build-docker:
    name: ğŸ³ Docker Build & Push
    runs-on: ubuntu-latest
    needs: [test-app] # <--- SÃ©curitÃ© : si le test Ã©choue, on ne build pas
    
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # VÃ©rifie le chemin du Dockerfile de ton binÃ´me
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/laravel-app:latest